name: CI/Deno

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  nodejs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: "v2.x"
    - run: deno test test/deno_test.ts

