name: CI

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  nodejs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '22'
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node-version }}
    - run: npm install -g nyc
    - run: npm ci
    - run: npm run test:cover
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./coverage
